Adjusting to new xacros
shadow-robot/sr_hand_detector pull request #29
Opened 2021-11-19 15:07 UTC by mikramarc

## Proposed changes

Adjusting autodetector to pass in new flags to work with new xacros. Some additional cleanup.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added automated tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2021-11-25 16:49 UTC, beatrizleon approved these changes

2021-11-26 10:01 UTC, giusebar requested changes

2021-11-26 10:01 UTC, giusebar commented on include/sr_hand_detector/sr_hand_detector.h
> +    uint8 ebuf_[MAXBUF];
why not setting maxbuf as const as well?

2021-11-26 10:01 UTC, giusebar commented on src/sr_hand_detector/sr_hand_autodetect.cpp
> +  std::string result;
we should check if vec size is 0 and return None?

2021-11-26 10:01 UTC, giusebar commented on src/sr_hand_detector/sr_hand_autodetect.cpp
> +  if (hand_info["mapping_path"])
what happens if there is no mapping path?

2021-11-26 10:01 UTC, giusebar commented on src/sr_hand_detector/sr_hand_autodetect.cpp
> +  std::string result;
just assuming there might be an extreme case in which people are able to lunch a hand with no fingers (e.g. phantom). if that is not possible in the xacro launch then should be ok.

2021-11-26 10:12 UTC, giusebar approved these changes

2021-11-29 11:22 UTC, biofotis approved these changes

2021-11-29 11:22 UTC, merged